---
title: Knowledge
description: Jekyll documentation theme for organizations, startups, and personal projects.
url: 
baseurl: 
lang: en
logo: /uploads/logo-main.svg
logo_mark: /uploads/logo-mark.svg
permalink: "/:title/"

social:
  twitter: "#"
  facebook: "#"
  instagram: "#"
  github: "#"
  dribbble: "#"

google_analytics: 

markdown: kramdown
highlighter: rouge

toc:
 min_level: 1
 max_level: 3
 list_class: toc

plugins:
- jekyll-seo-tag
- jekyll-toc

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- CHANGELOG
- LICENSE
- README
- "/docs"

livereload: true

collections:
  docs:
    output: true
    permalink: /:name

# Defaults
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
      toc: true
